[package]
name = "ksr-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
#futures = "0.3.31"
slint = "1.9.1"
#sqlx = "0.8.2"
#tokio = { version = "1.42.0", features = ["full"] }

[build-dependencies]
slint-build = "1.9.1"
