[package]
name = "ksr-rs"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["common"]

[dependencies]
slint = "1.9.1"
common = { path = "common/" }

[build-dependencies]
slint-build = "1.9.1"
